name: Generate Snake

on:
  push:
    branches: 
      - main
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake contribution graph (dengan kotak kosong hitam)
      - name: Generate snake graph
        uses: Platane/snk@v3
        with:
          github_user_name: IffaAstura
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          color_snake: "#39FF14" # warna ular (neon hijau contoh)
          color_dots: "#000000 #40c463 #30a14e #216e39 #0e4429"
          # urutan color_dots: kosong, level-1, level-2, level-3, level-4

      # Deploy to GitHub Pages branch (output branch)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
