name: Generate Snake

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake graph (kotak kosong hitam)
        uses: Platane/snk@v3
        with:
          github_user_name: IffaAstura
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          palette: |
            {
              "background": "#000000",
              "snake": "#39FF14",
              "dots": ["#000000", "#40c463", "#30a14e", "#216e39", "#0e4429"]
            }

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
